python3 -m kg_smile.kg_smile_permutation --dataset "synthetic" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/synthetic/delete_ops_ft --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/new_sample_40_synthetic_ft.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/synthetic_ft_kg_smile_permutation.json

python3 -m kg_smile.kg_smile_permutation --dataset "synthetic" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/synthetic/all_ops_ff --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_100_synthetic_ff.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/synthetic_ff_kg_smile_permutation.json



python3 -m kg_smile.kg_smile_permutation --dataset "hotpotqa" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/hotpotqa/delete_ops_ft --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_50_hotpotqa_ft.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/hotpotqa_ft_kg_smile_permutation.json

python3 -m kg_smile.kg_smile_permutation --dataset "hotpotqa" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/hotpotqa/all_ops_ff --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_60_hotpotqa_ff.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/hotpotqa_ff_kg_smile_permutation.json



python3 -m kg_smile.kg_smile_permutation --dataset "musique" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/musique/delete_ops_ft --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/new_sample_70_musique_ft.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/musique_ft_kg_smile_permutation.json

python3 -m kg_smile.kg_smile_permutation --dataset "musique" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/musique/all_ops_ff --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_90_musique_ff.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/musique_ff_kg_smile_permutation.json


python3 -m kg_smile.kg_smile_permutation --dataset "2wiki" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/2wiki/delete_ops_ft --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_45_2wiki_ft.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/2wiki_ft_kg_smile_permutation.json

python3 -m kg_smile.kg_smile_permutation --dataset "2wiki" --rag-mode "hybrid" --top-k 2 --input-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/2wiki/all_ops_ff --questions-file /home/gbalanos/GloRAG-Ex/code/src/sampled_questions/sample_100_2wiki_ff.json --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki/graph_chunk_entity_relation.graphml --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/permutations/2wiki_ff_kg_smile_permutation.json