python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/musique/all_ops_ff --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique/graph_chunk_entity_relation.graphml --explanation-mode "ff" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_musique_ff.json 

python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/musique/delete_ops_ft --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique/graph_chunk_entity_relation.graphml --explanation-mode "ft" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_musique_ft.json 


python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/hotpotqa/all_ops_ff --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa/graph_chunk_entity_relation.graphml --explanation-mode "ff" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_hotpotqa_ff.json 

python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/hotpotqa/delete_ops_ft --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa/graph_chunk_entity_relation.graphml --explanation-mode "ft" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_hotpotqa_ft.json 


python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/synthetic/all_ops_ff --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic/graph_chunk_entity_relation.graphml --explanation-mode "ff" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_synthetic_ff.json 

python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/synthetic/delete_ops_ft --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic/graph_chunk_entity_relation.graphml --explanation-mode "ft" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_synthetic_ft.json

python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/2wiki/delete_ops_ft --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki/graph_chunk_entity_relation.graphml --explanation-mode "ft" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_2wiki_ft.json

python3 -m kg_smile.runner run --explanation-dir /home/gbalanos/GloRAG-Ex/code/src/counterfactuals/results/2wiki/all_ops_ff --kg-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki --kg-graphml /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki/graph_chunk_entity_relation.graphml --explanation-mode "ff" --output /home/gbalanos/GloRAG-Ex/competitors/kg_smile/results/kg_smile_2wiki_ff.json