python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/synthetic/synthetic_remove_sentence_analysis.json --pool-sent /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/synthetic_kg_noise_sentences.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic --granularity "sentence" --noise-levels "0.1,0.2,0.3,0.5" --dataset "synthetic" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_synthetic_sent.json

python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/synthetic/synthetic_remove_paragraph_analysis.json --pool-para /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/synthetic_kg_noise_paragraphs.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/synthetic --granularity "paragraph" --noise-levels "0.1,0.2,0.3,0.5" --dataset "synthetic" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_synthetic_para.json



python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/hotpotqa/hotpotqa_remove_sentence_analysis.json --pool-sent /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/hotpotqa_kg_noise_sentences.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa --granularity "sentence" --noise-levels "0.1,0.2,0.3,0.5" --dataset "hotpotqa" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_hotpotqa_sent.json

python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/hotpotqa/hotpotqa_remove_paragraph_analysis.json --pool-para /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/hotpotqa_kg_noise_paragraphs.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/hotpotqa --granularity "paragraph" --noise-levels "0.1,0.2,0.3,0.5" --dataset "hotpotqa" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_hotpotqa_para.json



python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/musique/musique_remove_sentence_analysis.json --pool-sent /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/musique_kg_noise_sentences.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique --granularity "sentence" --noise-levels "0.1,0.2,0.3,0.5" --dataset "musique" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_musique_sent.json

python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/musique/musique_remove_paragraph_analysis.json --pool-para /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/musique_kg_noise_paragraphs.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/musique --granularity "paragraph" --noise-levels "0.1,0.2,0.3,0.5" --dataset "musique" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_musique_para.json

python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/2wiki/2wiki_remove_sentence_analysis.json --pool-sent /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/2wiki_kg_noise_sentences.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki --granularity "sentence" --noise-levels "0.1,0.2,0.3,0.5" --dataset "2wiki" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_2wiki_sent.json

python3 quality_metrics/ragex_noise_resistance.py --input /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/experiments/2wiki/2wiki_remove_paragraph_analysis.json --pool-para /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/noise_pool/2wiki_kg_noise_paragraphs.csv --working-dir /home/gbalanos/GloRAG-Ex/code/KGs/lightrag/2wiki --granularity "paragraph" --noise-levels "0.1,0.2,0.3,0.5" --dataset "2wiki" --output /home/gbalanos/GloRAG-Ex/competitors/RAGEX-RAGE-SHAPLEY/LLM/quality_metrics/robustness_ragex/robustness_rag_ex_2wiki_para.json